# Generated by Django 4.1.5 on 2023-02-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0002_product_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buyer",
            old_name="pin",
            new_name="pincode",
        ),
    ]
