# Generated by Django 4.1.5 on 2023-02-15 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0003_rename_pin_buyer_pincode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("orderStatus", models.CharField(max_length=50)),
                ("paymentMode", models.CharField(max_length=20)),
                ("paymentStatus", models.CharField(max_length=10)),
                (
                    "rppid",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("totalAmount", models.IntegerField()),
                ("shippingAmount", models.IntegerField()),
                ("finalAmount", models.IntegerField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MainApp.buyer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckoutProducts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("qty", models.IntegerField()),
                ("total", models.IntegerField()),
                ("pic", models.CharField(max_length=50)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MainApp.checkout",
                    ),
                ),
            ],
        ),
    ]
