# Generated by Django 4.1.5 on 2023-02-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0007_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="pincode",
            field=models.CharField(max_length=20),
        ),
    ]
