# Generated by Django 4.1.5 on 2023-02-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0008_alter_buyer_pincode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactus",
            old_name="date",
            new_name="time",
        ),
    ]
