# Generated by Django 4.1.5 on 2023-02-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0009_rename_date_contactus_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(default=9876543),
        ),
    ]
