# Generated by Django 4.1.5 on 2023-02-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0010_buyer_otp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buyer",
            old_name="pincode",
            new_name="pin",
        ),
    ]
